### ISSUE TITLE
[WinError 2] Failed to read the generated srt file

### ISSUE THREAD

**Issue by fagundes-dev** [Minhal-sami1/viralizeit#1]
![17129993930975862174511550200111](https://github.com/Minhal-sami1/viralizeit/assets/82334819/0e8d1dbd-942f-4e23-b4eb-e99db457d9eb)

**Comment by Minhal-sami1** [comment]
Which Python version are you using ?
Try using python 3.10 and use a virtual env for this app. 
Let me know what happens after that
thanks

**Comment by AbdulRKB** [comment]
Hello @fagundes-dev, please can you answer @Minhal-sami1. If we do not hear back, we may need to assume the issue has been resolved in order to close this issue. 

Thank You
